---
- name: firewall disable
  shell: yes | ufw disable

- name: firewall reset
  shell: yes | ufw reset

- name: copy ssh conf
  template: src=ufw_openssh.j2 dest=/etc/ufw/applications.d/openssh-server owner=root group=root mode=0644
  when: ssh_port != 22

- name: firewall allow ssh
  command: ufw allow openssh

- name: firewall deny all
  command: ufw default deny

# - name: firewall enable
#   shell: yes | ufw enable
